import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  counters: defineTable({ name: v.string(), value: v.number() }).index("by_name", ["name"]),
  organizations: defineTable({
    legacyId: v.number(),
    name: v.string(),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]),
  users: defineTable({
    legacyId: v.number(),
    username: v.string(),
    usernameLower: v.string(),
    passwordHash: v.string(),
    displayName: v.string(),
    role: v.union(v.literal("admin"), v.literal("mod"), v.literal("user")),
    departmentId: v.union(v.number(), v.null()),
    permissionGroupId: v.union(v.number(), v.null()),
    organizationId: v.union(v.number(), v.null()),
    active: v.number(),
    mustChangePassword: v.number(),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_username", ["usernameLower"]),
  sessions: defineTable({
    token: v.string(),
    userId: v.number(),
    createdAt: v.string(),
    expiresAt: v.string(),
  }).index("by_token", ["token"]).index("by_user", ["userId"]),
  loginAttempts: defineTable({
    usernameLower: v.string(),
    createdAt: v.string(),
  }).index("by_username", ["usernameLower"]),
  courses: defineTable({
    legacyId: v.number(),
    slug: v.string(),
    code: v.string(),
    title: v.string(),
    tagline: v.string(),
  }).index("by_slug", ["slug"]).index("by_legacy", ["legacyId"]),
  lessons: defineTable({
    legacyId: v.number(),
    courseId: v.number(),
    number: v.number(),
    title: v.string(),
    framework: v.string(),
    summary: v.string(),
    groupName: v.string(),
    hasReport: v.number(),
    storageKey: v.string(),
    contentVersion: v.string(),
    schemaVersion: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_course_number", ["courseId", "number"]),
  cohorts: defineTable({
    legacyId: v.number(),
    organizationId: v.number(),
    courseId: v.number(),
    name: v.string(),
    unlockMode: v.union(v.literal("all_open"), v.literal("sequential"), v.literal("scheduled")),
    reviewEnabled: v.number(),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]),
  lessonUnlocks: defineTable({
    cohortId: v.number(),
    lessonId: v.number(),
    unlockAt: v.union(v.string(), v.null()),
  }).index("by_cohort_lesson", ["cohortId", "lessonId"]),
  enrollments: defineTable({
    legacyId: v.number(),
    userId: v.number(),
    cohortId: v.number(),
    courseId: v.number(),
    memberRole: v.union(v.literal("learner"), v.literal("coach")),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_user_course", ["userId", "courseId"]).index("by_user", ["userId"]).index("by_cohort", ["cohortId"]),
  lessonAnswers: defineTable({
    legacyId: v.number(),
    userId: v.number(),
    courseId: v.number(),
    lessonId: v.number(),
    schemaVersion: v.string(),
    answersJson: v.string(),
    currentPhase: v.string(),
    phasesDoneJson: v.string(),
    progressPercent: v.number(),
    status: v.string(),
    completedAt: v.union(v.string(), v.null()),
    updatedAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_user", ["userId"]).index("by_user_lesson", ["userId", "lessonId"]),
  lessonSubmissions: defineTable({
    legacyId: v.number(),
    userId: v.number(),
    lessonId: v.number(),
    cohortId: v.union(v.number(), v.null()),
    schemaVersion: v.string(),
    contentVersion: v.string(),
    answersJson: v.string(),
    phase: v.string(),
    progressPercent: v.number(),
    submittedAt: v.string(),
    reviewStatus: v.string(),
  }).index("by_legacy", ["legacyId"]),
  coachFeedback: defineTable({
    legacyId: v.number(),
    submissionId: v.number(),
    authorId: v.number(),
    body: v.string(),
    createdAt: v.string(),
  }).index("by_submission", ["submissionId"]),
  activityLogs: defineTable({
    legacyId: v.number(),
    actorId: v.union(v.number(), v.null()),
    action: v.string(),
    targetType: v.union(v.string(), v.null()),
    targetId: v.union(v.string(), v.null()),
    detail: v.union(v.string(), v.null()),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_actor", ["actorId"]),
  departments: defineTable({
    legacyId: v.number(),
    organizationId: v.union(v.number(), v.null()),
    name: v.string(),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]),
  permissionGroups: defineTable({
    legacyId: v.number(),
    name: v.string(),
    description: v.string(),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_name", ["name"]),
  permissionGroupMenus: defineTable({
    groupId: v.number(),
    menuKey: v.string(),
  }).index("by_group", ["groupId"]),
  tasks: defineTable({
    legacyId: v.number(),
    title: v.string(),
    body: v.string(),
    assigneeId: v.number(),
    authorId: v.number(),
    status: v.union(v.literal("open"), v.literal("done")),
    dueAt: v.union(v.string(), v.null()),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_assignee", ["assigneeId"]),
  cmsBlocks: defineTable({
    key: v.string(),
    locale: v.union(v.literal("vi"), v.literal("en")),
    body: v.string(),
    updatedAt: v.string(),
  }).index("by_key_locale", ["key", "locale"]),
  cmsAnnouncements: defineTable({
    legacyId: v.number(),
    title: v.string(),
    body: v.string(),
    locale: v.union(v.literal("vi"), v.literal("en")),
    published: v.number(),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]),
  cmsLessons: defineTable({
    number: v.number(),
    titleVi: v.string(),
    titleEn: v.string(),
    summaryVi: v.string(),
    summaryEn: v.string(),
    published: v.number(),
    updatedAt: v.string(),
  }).index("by_number", ["number"]),
  discussionChannels: defineTable({
    legacyId: v.number(),
    cohortId: v.number(),
    kind: v.union(v.literal("class"), v.literal("group")),
    name: v.string(),
    archived: v.number(),
    createdBy: v.number(),
    createdAt: v.string(),
  }).index("by_legacy", ["legacyId"]).index("by_cohort", ["cohortId"]),
  discussionMembers: defineTable({
    channelId: v.number(),
    userId: v.number(),
    createdAt: v.string(),
  }).index("by_channel", ["channelId"]).index("by_channel_user", ["channelId", "userId"]),
  discussionMessages: defineTable({
    legacyId: v.number(),
    channelId: v.number(),
    authorId: v.number(),
    body: v.string(),
    createdAt: v.string(),
  }).index("by_channel", ["channelId"]),
});
