/**
 * Generates lib/studios/validators.generated.ts from the original studio HTML files.
 *
 * Each studio ships its own `validate(doc)` (the rule it applies when importing JSON). We copy that
 * function, plus only the top-level constants/functions it depends on, verbatim, so the server and the
 * browser check a document with exactly the studio's own rules. Nothing that touches the DOM is copied.
 *
 *   npx tsx scripts/studio-validators.ts          # rewrite the generated file
 *   npx tsx scripts/studio-validators.ts --check  # fail if the generated file is stale
 */
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { studioScript } from "../lib/studios/script";

/** Studio id -> [source file, name of the studio's own import check]. */
export const STUDIO_FILES: Record<string, [string, string]> = {
  mrim: ["source/bmdo-k03-studios/mrim/index.html", "validate"],
  mair: ["source/bmdo-k03-studios/mair/index.html", "validate"],
  mcasing: ["source/bmdo-k03-studios/mcasing/index.html", "validate"],
  mtread: ["source/bmdo-k03-studios/mtread/index.html", "validate"],
  prim: ["source/bmdo-k03-studios/prim/index.html", "valid"],
  pcasing: ["source/bmdo-k03-studios/pcasing/index.html", "valid"],
};

const OUT = "lib/studios/validators.generated.ts";


type Decl = { name: string; text: string; pos: number; deps: Set<string> };

function collect(script: string) {
  const file = ts.createSourceFile("studio.js", script, ts.ScriptTarget.ES2022, true, ts.ScriptKind.JS);
  const decls = new Map<string, Decl>();
  const idents = (node: ts.Node) => {
    const out = new Set<string>();
    const walk = (n: ts.Node) => {
      if (ts.isIdentifier(n)) {
        // skip property names in a.b and {key: v}
        const parent = n.parent;
        const isProp = parent && ((ts.isPropertyAccessExpression(parent) && parent.name === n) || (ts.isPropertyAssignment(parent) && parent.name === n));
        if (!isProp) out.add(n.text);
      }
      ts.forEachChild(n, walk);
    };
    walk(node);
    return out;
  };
  for (const statement of file.statements) {
    if (ts.isFunctionDeclaration(statement) && statement.name) {
      decls.set(statement.name.text, { name: statement.name.text, text: statement.getText(file), pos: statement.getStart(file), deps: idents(statement) });
    } else if (ts.isVariableStatement(statement)) {
      for (const d of statement.declarationList.declarations) {
        if (!ts.isIdentifier(d.name)) continue;
        // Declarations are re-emitted as `const`; a top-level `let` reassigned later is never a validator dependency.
        decls.set(d.name.text, { name: d.name.text, text: `const ${d.getText(file)};`, pos: d.getStart(file), deps: d.initializer ? idents(d.initializer) : new Set() });
      }
    }
  }
  return decls;
}

export function validatorSource(script: string, entry: string) {
  const decls = collect(script);
  if (!decls.has(entry)) throw new Error(`studio has no ${entry}()`);
  const need = new Set<string>();
  const visit = (name: string) => {
    if (need.has(name) || !decls.has(name)) return;
    need.add(name);
    for (const dep of decls.get(name)!.deps) visit(dep);
  };
  visit(entry);
  const parts = [...need].map((name) => decls.get(name)!).sort((a, b) => a.pos - b.pos);
  const forbidden = parts.filter((part) => /\b(document|localStorage|window)\b/.test(part.text) && part.name !== "$" && part.name !== "$$");
  if (forbidden.length) throw new Error(`validator depends on DOM code: ${forbidden.map((p) => p.name).join(", ")}`);
  return parts.map((part) => part.text).join("\n");
}

export function generate(root = process.cwd()) {
  const blocks = Object.entries(STUDIO_FILES).map(([id, [file, entry]]) => {
    const script = studioScript(fs.readFileSync(path.join(root, file), "utf8"));
    return `/** ${file} · ${entry}() */\nconst ${id} = (() => {\n"use strict";\n${validatorSource(script, entry)}\nreturn ${entry};\n})();`;
  });
  return `// @ts-nocheck\n/* eslint-disable */\n// GENERATED by scripts/studio-validators.ts from the original studio files. Do not edit by hand.\n// Each block is the studio's own validate() and the constants it reads, copied verbatim.\n\n${blocks.join("\n\n")}\n\nexport const STUDIO_VALIDATORS: Record<string, (doc: unknown) => unknown> = { ${Object.keys(STUDIO_FILES).join(", ")} };\n`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname);
if (isMain) {
  const next = generate();
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (current !== next) { console.error(`${OUT} is stale. Run: npx tsx scripts/studio-validators.ts`); process.exit(1); }
    console.log(`${OUT} is up to date`);
  } else {
    fs.writeFileSync(OUT, next);
    console.log(`wrote ${OUT}`);
  }
}
